@Restaurants.API_HostAddress = https://localhost:7282

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Biriyani 2",
  "Description": "Boiled",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "Test@gmail.com",
  "ContactNUmber": "2345678901",
  "City": "London",
  "Street": "WC2N 5ert",
  "PostalCode": "WC2N 5DU"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name": "Biriyani 3",
  "Description": "Spicy",
  "HasDelivery": true

}

###
