@Restaurants.API_HostAddress = https://localhost:7282
@token = CfDJ8L5DWrGvpS5HqY3lzUdga0cOnNBLIPBsdNo5QS0__65BM54-qmuuCA1fSR-pacvJSby2lTyl-pNb7kytlve-npg7k8TL4OxktG1i6SsqVe42VoMmU2IttVrB_eBPA2Tmpvgv5Jb-rQrl1kITEkJ5Sb6WVlj1WuqYtkwlbR8jQemy1cASF0yErAqWpxUZ4Y_NsfgbQzdQlp2q-NCtcS5fYPJEHukoYtd8MVuza-ncR1ySNKUjRLXx_47YzK-mldyLt6nXCWt_p7iLuDGJHUInTjgadvnVZV9w9ERYjlt24eM6EfpEedOFqKgmasSmNsriAC6Wt015FRmEhLtBx9F0OOaPRMaXjzydidNCVc68KnuFLHJrLcbmVZskR3sztGYcq2Gp5uQSXtVcydZbHA-23YV2KwweD-wxKxPvnMpo3QQ2vixVPZyfERaHbo0W9gt36qPMPmv1TGAjblvAMPxnCAIgduzl72Npmv2bXSwkgGj-Y2vr6jrotDapnrfOUT75-whdCIq17vKVrFgXJab7WxE686PzXLpYAukk90EhbVnBMTYTLcwpVv9qWRL8O4WzbFpjow5EJ_xdopfjOt39LJslvQWGnKHMIw6PwER8ZRDX4mBlmWsgnZdtCF8h-7xd8oub-8CradfU7wMbUEB2ugk5TOxq77aNzot3d1OlONnzAEIBEcTpsYNwHgleRqz2cA

####    Restaurant     #####

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization:  Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2
Authorization:  Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Biriyani 2",
  "Description": "Boiled",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "Test@gmail.com",
  "ContactNUmber": "2345678901",
  "City": "London",
  "Street": "WC2N 5ert",
  "PostalCode": "WC2N 5DU"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/7
Content-Type: application/json

{
  "Name": "Biriyani 3",
  "Description": "Spicy",
  "HasDelivery": true

}

###

#####  Dish   #####

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name":"Paneer Manchurian",
  "Description":"Chenese food",
  "Price":280,
  "KiloCalories": 370
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/10

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###


POST {{Restaurants.API_HostAddress}}/api/Identity/register
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "Test@01"
}

###

POST {{Restaurants.API_HostAddress}}/api/Identity/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test@1"
}

PATCH {{Restaurants.API_HostAddress}}/user
Content-Type: application/json

{
  //UpdateUserDetailsCommand
}

###
